name: Orpheusbetter Docker Image

on:
  push:
    workflow_dispatch:
    branches:
      - master
    paths:
      - ".github/workflows/main.yml"
      - "Dockerfile"

jobs:
  Orpheusbetter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --tag starkayc/orpheusbetter:latest

        docker push starkayc/orpheusbetter:latest